const { db } = require('./src/config/firebase');

const puntos = [
  {
    "nombre": "Centro Verde Norte",
    "lat": -31.3364,
    "lng": -64.2272,
    "tipos": ["Plástico", "Vidrio", "Cartón", "Papel", "Metal"],
    "direccion": "Bv. Los Alemanes 3387, Zona Norte",
    "horarios": "Lun-Vie 8-20hs, Sáb 8-12hs",
    "observaciones": "Recepción de residuos secos. Entrada accesible para vehículos.",
    "id": "cv-norte-001",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Centro Verde Sur",
    "lat": -31.4721,
    "lng": -64.1965,
    "tipos": ["Plástico", "Vidrio", "Cartón", "Papel", "Metal"],
    "direccion": "Av. Belardinelli 4776, Barrio Jardín",
    "horarios": "Lun-Vie 8-20hs, Sáb 8-12hs",
    "observaciones": "Zona sur, cerca del Jockey Club.",
    "id": "cv-sur-002",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Centro Verde Este",
    "lat": -31.4358,
    "lng": -64.1352,
    "tipos": ["Plástico", "Vidrio", "Cartón", "Papel", "Metal"],
    "direccion": "Av. Circunvalación 6591 (Colectora SE)",
    "horarios": "Lun-Sáb 9-19hs",
    "observaciones": "Entrada por colectora. Gran capacidad.",
    "id": "cv-este-003",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Centro Verde Telas",
    "lat": -31.4785,
    "lng": -64.2082,
    "tipos": ["Textil"],
    "direccion": "Av. Armada Argentina 1637",
    "horarios": "Lun-Vie 8-18hs",
    "observaciones": "Exclusivo retazos de tela y ropa. Frente al CPC Villa El Libertador.",
    "id": "cv-telas-004",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Centro Verde Ecofem",
    "lat": -31.3854,
    "lng": -64.1681,
    "tipos": ["Plástico", "Vidrio", "Cartón", "Papel", "Metal"],
    "direccion": "Av. Alem 1447, Barrio Talleres Oeste",
    "horarios": "Lun-Vie 8-20hs, Sáb 8-12hs",
    "observaciones": "Operado por cooperativa de mujeres.",
    "id": "cv-ecofem-005",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CTR Rancagua",
    "lat": -31.3652,
    "lng": -64.1481,
    "tipos": ["Electrónicos", "Metal", "Orgánico", "Plástico", "Vidrio", "Cartón"],
    "direccion": "Av. Circunvalación y Av. Rancagua",
    "horarios": "Lun-Dom 8-20hs",
    "observaciones": "Aceptan restos de poda y voluminosos.",
    "id": "ctr-rancagua-006",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CTR Villa Unión",
    "lat": -31.4238,
    "lng": -64.2452,
    "tipos": ["Electrónicos", "Metal", "Orgánico", "Plástico", "Vidrio", "Cartón"],
    "direccion": "Av. Circunvalación y Av. Revolución Libertadora",
    "horarios": "Lun-Dom 8-20hs",
    "observaciones": "Centro de transferencia zona Oeste. Aceptan poda y neumáticos.",
    "id": "ctr-villa-union-007",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Parque de las Tejas",
    "lat": -31.4361,
    "lng": -64.1942,
    "tipos": ["Plástico", "Vidrio", "Cartón", "Papel", "Metal"],
    "direccion": "Bv. Chacabuco 1300",
    "horarios": "Abierto 24hs",
    "observaciones": "Estación de reciclaje en el parque.",
    "id": "eco-tejas-008",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Plaza Rivadavia",
    "lat": -31.3965,
    "lng": -64.1863,
    "tipos": ["Plástico", "Vidrio", "Cartón", "Papel"],
    "direccion": "Mariano Fragueiro y Baigorrí, Alta Córdoba",
    "horarios": "Abierto 24hs",
    "observaciones": "Contenedores en plaza.",
    "id": "eco-rivadavia-009",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde La Calera",
    "lat": -31.3448,
    "lng": -64.3331,
    "tipos": ["Plástico", "Vidrio", "Metal", "Cartón"],
    "direccion": "Av. San Martín 450, La Calera",
    "horarios": "Lun-Sáb 9-13hs",
    "observaciones": "Punto municipal.",
    "id": "pv-calera-010",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Contenedor Palacio Municipal",
    "lat": -31.4163,
    "lng": -64.1904,
    "tipos": ["Electrónicos"],
    "direccion": "Marcelo T. de Alvear 120",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Recepción exclusiva de pilas y baterías en mesa de entrada.",
    "id": "pilas-centro-011",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC Argüello",
    "lat": -31.3551,
    "lng": -64.2384,
    "tipos": ["Plástico", "Papel", "Cartón", "Aceite"],
    "direccion": "Av. Rafael Núñez 6500",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Estacionamiento del CPC. Aceptan aceite vegetal usado.",
    "id": "cpc-arguello-012",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Plaza de la Intendencia",
    "lat": -31.4192,
    "lng": -64.1915,
    "tipos": ["Plástico", "Vidrio", "Papel", "Cartón", "Metal"],
    "direccion": "Caseros esq. Bolívar",
    "horarios": "Abierto 24hs",
    "observaciones": "Punto muy concurrido en el centro. Frente a Tribunales.",
    "id": "eco-intendencia-013",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Plaza Colón",
    "lat": -31.4085,
    "lng": -64.1972,
    "tipos": ["Plástico", "Vidrio", "Papel", "Cartón"],
    "direccion": "Av. Colón 800, Alberdi",
    "horarios": "Abierto 24hs",
    "observaciones": "Contenedores soterrados y campanas.",
    "id": "eco-colon-014",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Parque Sarmiento",
    "lat": -31.4285,
    "lng": -64.1782,
    "tipos": ["Plástico", "Vidrio", "Metal"],
    "direccion": "Av. Deodoro Roca (Cerca del Teatro Griego)",
    "horarios": "Abierto 24hs",
    "observaciones": "Ideal para residuos de picnics o bebidas.",
    "id": "eco-sarmiento-015",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Plaza Jerónimo del Barco",
    "lat": -31.4081,
    "lng": -64.2155,
    "tipos": ["Plástico", "Vidrio", "Papel", "Cartón"],
    "direccion": "Av. Colón 2700, Alto Alberdi",
    "horarios": "Abierto 24hs",
    "observaciones": "Punto de referencia en zona oeste.",
    "id": "eco-jeronimo-016",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Parque de las Naciones",
    "lat": -31.3852,
    "lng": -64.2305,
    "tipos": ["Plástico", "Vidrio", "Papel"],
    "direccion": "Av. Sagrada Familia y Mariano Larra",
    "horarios": "Abierto 24hs",
    "observaciones": "Zona Cerro de las Rosas/Urca.",
    "id": "eco-naciones-017",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Paseo del Buen Pastor",
    "lat": -31.4245,
    "lng": -64.1882,
    "tipos": ["Plástico", "Vidrio", "Metal"],
    "direccion": "Av. Hipólito Yrigoyen 325",
    "horarios": "Abierto 24hs",
    "observaciones": "Contenedores diferenciados en zona turística.",
    "id": "eco-buenpastor-018",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC Villa El Libertador",
    "lat": -31.4788,
    "lng": -64.2090,
    "tipos": ["Electrónicos", "Aceite"],
    "direccion": "Av. Armada Argentina y Lago Argentino",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Recepción de pilas y aceite usado.",
    "id": "cpc-libertador-019",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC Centro América",
    "lat": -31.3685,
    "lng": -64.1752,
    "tipos": ["Plástico", "Papel", "Cartón", "Electrónicos"],
    "direccion": "Av. Juan B. Justo y Parravicini",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Zona norte/noreste.",
    "id": "cpc-centroamerica-020",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC Monseñor Pablo Cabrera",
    "lat": -31.3782,
    "lng": -64.2055,
    "tipos": ["Plástico", "Papel", "Cartón"],
    "direccion": "Av. Monseñor Pablo Cabrera 4800",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Punto de acopio en zona Poeta Lugones.",
    "id": "cpc-monseñor-021",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC Ruta 20",
    "lat": -31.4288,
    "lng": -64.2375,
    "tipos": ["Electrónicos", "Aceite", "Plástico"],
    "direccion": "Av. Fuerza Aérea 4300",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Entrada principal. Contenedor de pilas.",
    "id": "cpc-ruta20-022",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC Empalme",
    "lat": -31.4395,
    "lng": -64.1290,
    "tipos": ["Plástico", "Papel", "Cartón"],
    "direccion": "Av. Amadeo Sabattini 4600",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Zona sureste, arco de Córdoba.",
    "id": "cpc-empalme-023",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC Pueyrredón",
    "lat": -31.4055,
    "lng": -64.1560,
    "tipos": ["Electrónicos", "Plástico"],
    "direccion": "Rincón y Armenia, B° Pueyrredón",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Cerca del Hospital Transito Cáceres.",
    "id": "cpc-pueyrredon-024",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Plaza Alem",
    "lat": -31.3985,
    "lng": -64.1555,
    "tipos": ["Plástico", "Vidrio", "Papel"],
    "direccion": "Pringles y Potosí, B° Pueyrredón",
    "horarios": "Abierto 24hs",
    "observaciones": "Ecopunto barrial.",
    "id": "eco-alem-025",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ciudad Universitaria (Comedor)",
    "lat": -31.4385,
    "lng": -64.1905,
    "tipos": ["Plástico", "Papel", "Cartón", "Orgánico"],
    "direccion": "Av. Valparaíso s/n (Detrás del Comedor UNC)",
    "horarios": "Lun-Vie 9-18hs",
    "observaciones": "Puntos de Gestión de Residuos UNC. Compostaje in situ.",
    "id": "unc-comedor-026",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Plaza San Martín",
    "lat": -31.4168,
    "lng": -64.1835,
    "tipos": ["Plástico", "Papel", "Electrónicos"],
    "direccion": "Independencia y San Jerónimo",
    "horarios": "Abierto 24hs",
    "observaciones": "Pleno centro histórico. Contenedores de pilas cercanos.",
    "id": "eco-sanmartin-027",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde Villa Allende",
    "lat": -31.2945,
    "lng": -64.2940,
    "tipos": ["Plástico", "Vidrio", "Metal", "Cartón"],
    "direccion": "Av. Goycoechea 1810 (Polideportivo)",
    "horarios": "Lun-Sáb 8-18hs",
    "observaciones": "Punto de acopio municipal Villa Allende.",
    "id": "pv-villaallende-028",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde Mendiolaza",
    "lat": -31.2675,
    "lng": -64.3025,
    "tipos": ["Plástico", "Vidrio", "Metal"],
    "direccion": "Malvinas Argentinas 285",
    "horarios": "Lun-Vie 8-13hs",
    "observaciones": "Frente a la Municipalidad de Mendiolaza.",
    "id": "pv-mendiolaza-029",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Plaza Alberdi",
    "lat": -31.4082,
    "lng": -64.1755,
    "tipos": ["Plástico", "Vidrio", "Cartón"],
    "direccion": "Félix Frías y 24 de Septiembre",
    "horarios": "Abierto 24hs",
    "observaciones": "Corazón de Barrio General Paz.",
    "id": "eco-alberdi-030",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-01T00:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Jardín Botánico",
    "lat": -31.3915,
    "lng": -64.2492,
    "tipos": ["Plástico", "Vidrio", "Papel", "Cartón", "Metal"],
    "direccion": "Francisco Yunyent 5491, B° Quebrada de las Rosas",
    "horarios": "Lun-Vie 9-18hs",
    "observaciones": "Dentro del estacionamiento del Jardín Botánico.",
    "id": "eco-botanico-031",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T09:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Parque del Chateau",
    "lat": -31.3932,
    "lng": -64.2568,
    "tipos": ["Plástico", "Vidrio", "Metal"],
    "direccion": "Ramón Cárcano 1750",
    "horarios": "Lun-Dom 8-20hs",
    "observaciones": "Frente al Centro de Arte Contemporáneo.",
    "id": "eco-chateau-032",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T09:10:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Valle Escondido",
    "lat": -31.3785,
    "lng": -64.2750,
    "tipos": ["Plástico", "Papel", "Cartón"],
    "direccion": "Av. República de China 1400",
    "horarios": "Abierto 24hs",
    "observaciones": "Punto de reciclaje barrial zona oeste.",
    "id": "eco-valle-033",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T09:15:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Elías Yofre",
    "lat": -31.4552,
    "lng": -64.1825,
    "tipos": ["Plástico", "Vidrio", "Papel"],
    "direccion": "Elías Yofre 1050, B° Jardín",
    "horarios": "Abierto 24hs",
    "observaciones": "Zona comercial sur, frente al Paseo del Jockey.",
    "id": "eco-yofre-034",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T09:20:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Plaza Mariano Moreno",
    "lat": -31.4281,
    "lng": -64.1565,
    "tipos": ["Plástico", "Vidrio", "Papel"],
    "direccion": "San Jerónimo 2800, B° San Vicente",
    "horarios": "Abierto 24hs",
    "observaciones": "Frente al CPC San Vicente.",
    "id": "eco-sanvicente-035",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T09:25:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Plaza Gendarmería",
    "lat": -31.3858,
    "lng": -64.2025,
    "tipos": ["Plástico", "Papel", "Cartón"],
    "direccion": "Virgen de la Merced 2800, B° San Martín",
    "horarios": "Abierto 24hs",
    "observaciones": "Plaza principal del barrio.",
    "id": "eco-gendarmeria-036",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T09:30:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde Dinosaurio Mall",
    "lat": -31.3673,
    "lng": -64.2195,
    "tipos": ["Plástico", "Cartón", "Electrónicos", "Vidrio"],
    "direccion": "Rodríguez del Busto 4086, Alto Verde",
    "horarios": "Lun-Dom 10-22hs",
    "observaciones": "Estación de reciclaje en playa subterránea.",
    "id": "pv-dino-037",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T09:40:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde Carrefour Villa Urquiza",
    "lat": -31.3985,
    "lng": -64.2345,
    "tipos": ["Plástico", "Metal", "Pilas"],
    "direccion": "Av. Colón 4880",
    "horarios": "Lun-Dom 8-22hs",
    "observaciones": "Contenedores en el ingreso del Hipermercado.",
    "id": "pv-carrefour-urquiza-038",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T09:45:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde Carrefour Jardín",
    "lat": -31.4582,
    "lng": -64.1755,
    "tipos": ["Plástico", "Metal", "Pilas"],
    "direccion": "Av. O'Higgins 3765, Jardín Espinosa",
    "horarios": "Lun-Dom 8-22hs",
    "observaciones": "Estación de reciclaje en estacionamiento.",
    "id": "pv-carrefour-jardin-039",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T09:50:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde Carrefour Argüello",
    "lat": -31.3485,
    "lng": -64.2582,
    "tipos": ["Plástico", "Metal", "Pilas"],
    "direccion": "Recta Martinolli 7500",
    "horarios": "Lun-Dom 8-22hs",
    "observaciones": "Zona norte, contenedores diferenciados.",
    "id": "pv-carrefour-arguello-040",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T09:55:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Terminal de Ómnibus T1",
    "lat": -31.4235,
    "lng": -64.1765,
    "tipos": ["Plástico", "Papel", "Pilas"],
    "direccion": "Bv. Perón 380",
    "horarios": "Abierto 24hs",
    "observaciones": "Puntos internos en zona de boleterías.",
    "id": "eco-terminal-041",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T10:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC San Vicente",
    "lat": -31.4283,
    "lng": -64.1568,
    "tipos": ["Pilas", "Aceite"],
    "direccion": "San Jerónimo 2850",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Recepción de pilas y aceite vegetal.",
    "id": "cpc-sanvicente-042",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T10:10:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC Colón",
    "lat": -31.4015,
    "lng": -64.2255,
    "tipos": ["Plástico", "Pilas"],
    "direccion": "Av. Colón 5300",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Contenedor en entrada.",
    "id": "cpc-colon-043",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T10:15:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC Rancagua",
    "lat": -31.3825,
    "lng": -64.1525,
    "tipos": ["Plástico", "Papel", "Aceite"],
    "direccion": "Av. Rancagua 2900",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Recepción de materiales barrio Villa Corina/Patricios.",
    "id": "cpc-rancagua-044",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T10:20:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "CPC Guiñazú",
    "lat": -31.3055,
    "lng": -64.2050,
    "tipos": ["Plástico", "Pilas"],
    "direccion": "Av. Juan B. Justo 9654",
    "horarios": "Lun-Vie 8-14hs",
    "observaciones": "Zona extremo norte de la ciudad.",
    "id": "cpc-guinazu-045",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T10:25:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde La Calera - Barrio Industrial",
    "lat": -31.3520,
    "lng": -64.3250,
    "tipos": ["Plástico", "Vidrio"],
    "direccion": "Calle Pública s/n (Dispensario Industrial)",
    "horarios": "Lun-Vie 8-13hs",
    "observaciones": "Punto de acopio cerca del dispensario municipal.",
    "id": "pv-calera-industrial-046",
    "creadoPor": "admin-lacalera",
    "creadoEn": "2025-01-02T11:00:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde La Calera - Dumesnil",
    "lat": -31.3350,
    "lng": -64.3150,
    "tipos": ["Plástico", "Metal"],
    "direccion": "Av. Dumesnil (Plaza Principal)",
    "horarios": "Abierto 24hs",
    "observaciones": "Campanas de reciclaje zona Dumesnil.",
    "id": "pv-calera-dumesnil-047",
    "creadoPor": "admin-lacalera",
    "creadoEn": "2025-01-02T11:05:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde Villa Allende - Muni",
    "lat": -31.2952,
    "lng": -64.2965,
    "tipos": ["Plástico", "Vidrio", "Pilas"],
    "direccion": "Av. Goycoechea 586",
    "horarios": "Lun-Vie 8-13hs",
    "observaciones": "Contenedores en el patio de la Municipalidad.",
    "id": "pv-villaallende-muni-048",
    "creadoPor": "admin-villaallende",
    "creadoEn": "2025-01-02T11:10:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Punto Verde Saldán",
    "lat": -31.3050,
    "lng": -64.3080,
    "tipos": ["Plástico", "Vidrio"],
    "direccion": "Plaza Congresales de Tucumán",
    "horarios": "Abierto 24hs",
    "observaciones": "Punto verde en la plaza central de Saldán.",
    "id": "pv-saldan-049",
    "creadoPor": "admin-saldan",
    "creadoEn": "2025-01-02T11:15:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  },
  {
    "nombre": "Ecopunto Plaza Las Heras",
    "lat": -31.4050,
    "lng": -64.1850,
    "tipos": ["Plástico", "Vidrio", "Cartón"],
    "direccion": "Bv. Las Heras 150",
    "horarios": "Abierto 24hs",
    "observaciones": "Zona Cofico / Parque Las Heras.",
    "id": "eco-lasheras-050",
    "creadoPor": "admin-inicial",
    "creadoEn": "2025-01-02T11:20:00Z",
    "activo": true,
    "validaciones": 0,
    "invalidaciones": 0,
    "validadoPor": [],
    "invalidadoPor": [],
    "rating": "nuevo"
  }
];

async function seedPuntos() {
  try {
    console.log('Iniciando importación de puntos de reciclaje...');
    
    let count = 0;
    const batch = db.batch();
    
    for (const punto of puntos) {
      const docRef = db.collection('puntos').doc(punto.id);
      
      // No incluimos el id dentro del documento ya que es el ID del documento
      // Pero si se quiere mantener en la data:
      const data = { ...punto };
      
      // Convertir fechas si es necesario (el JSON tiene string ISO)
      // Firestore acepta strings ISO o objetos Date.
      
      batch.set(docRef, data);
      count++;
    }
    
    await batch.commit();
    
    console.log(`Se han importado ${count} puntos de reciclaje correctamente.`);
    process.exit(0);
  } catch (error) {
    console.error('Error al importar puntos:', error);
    process.exit(1);
  }
}

seedPuntos();

